### ISSUE TITLE
Genetics SE's disappear upon changing them.

### ISSUE THREAD

**Issue by KryptonOsmium** [Citadel-Station-13/Citadel-Station-13-5th-Port#86]
I'm sure most people know about this issue already, but I want to put it up here just to make sure. 

When you change people's SE's via the genetics consoles, they simply disappear for whatever reason. I dunno how long it has been an issue, but it's something to look in to. I personally think it might be something with the narky code, but I could be wrong since i'm not so experienced with code and what not.

**Comment by LetterJay** [comment]
fixed with #104
