### ISSUE TITLE
Lawyers are still open as a job

### ISSUE THREAD

**Issue by Zeldazackman** [Citadel-Station-13/Citadel-Station-13-5th-Port#98]
Oddly enough we've still got the job position of lawyer capable of being slected within the job selection menu as well as still being a randomly given job at round start despite removing their office completely from the station.

Its also able to still be an option in the ID console as well oddly enough.

**Comment by TalkingCactus** [comment]
It was intentional as a joke. You can't make fun of the lawyers for not having an office if there are no lawyers!

**Comment by TalkingCactus** [comment]
#116
